### PR TITLE
OTS-458: Fix for controls not working after screen share

### PR DESCRIPTION
**Pull request by andreaphillips**
## Pull request checklist

- [ ] All tests pass. Demo project builds and runs.
- [ ] I have resolved any merge conflicts. Confirmation: ____

## What's in this pull request?

>...

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/one-to-one-sample-apps/pull/156" target="_blank">ReviewNinja

**Comment by adrice727** [comment]
LGTM

**Comment by adrice727** [comment]
LGTM

**Comment by andreaphillips** [comment]
👍

**Pull request merged**
