### PR TITLE
Update README.md for all platforms - 1.2.0 release

### PR DESCRIPTION
**Pull request by marinaserranomontes**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts. Confirmation: ____

## What's in this pull request?

>...

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/one-to-one-sample-apps/pull/151" target="_blank">ReviewNinja

**Comment by Lucashuang0802** [comment]
👍

**Comment by Lucashuang0802** [comment]
iOS/README.md is updated.

**Comment by Lucashuang0802** [comment]
👍

**Comment by marinaserranomontes** [comment]
👍

**Pull request merged**
