### PR TITLE
[One-to-One-Example app] OTAcceleratorPackUtil using 2.0.0-beta4.

### PR DESCRIPTION
**Pull request by southfox**
Jira: https://tokbox.atlassian.net/browse/OTS-743
AppDelegate: create an acceleratorSession instance that is shared inside the example application.
Fixing project.pbxproj not included in the repository.

WIP: please do not merge.

Issues now:
- need to test a little bit more
- when you share video sometimes does not appear in the iOS example app
- sometimes the toolbar with the mute sound/video is duplicated.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/one-to-one-sample-apps/pull/159" target="_blank">ReviewNinja

**Comment by Lucashuang0802** [comment]
@southfox for `sometimes the toolbar with the mute sound/video is duplicated.`. You can control it by two properties: `showAudioVideoControl` and `handleAudioVideo`.

**Comment by Lucashuang0802** [comment]
@southfox need more info on the second item.

**Comment by southfox** [comment]
@Lucashuang0802 I'll update the PR with your suggestion, I think I can fix that issue with the toolbar duplicated.

**Comment by southfox** [comment]
Closing this PR, sending a new one now https://github.com/opentok/one-to-one-sample-apps/pull/161

**Pull request closed without merging**
