### PR TITLE
Update iOS/README.md

### PR DESCRIPTION
**Pull request by Lucashuang0802**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts. Confirmation: ____

## What's in this pull request?

> Update iOS/README.md

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/one-to-one-sample-apps/pull/154" target="_blank">ReviewNinja

**Comment by Lucashuang0802** [comment]
👍

**Comment by marinaserranomontes** [comment]
LGTM

**Comment by Lucashuang0802** [comment]
👍

**Pull request merged**
