### PR TITLE
Update to 1.2 and refactoring dirs

### PR DESCRIPTION
**Pull request by marinaserranomontes**
## Pull request checklist

- [ ] All tests pass. Demo project builds and runs.
- [ ] I have resolved any merge conflicts. Confirmation: ____

## What's in this pull request?

>...

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/one-to-one-sample-apps/pull/149" target="_blank">ReviewNinja

**Comment by Lucashuang0802** [comment]
@marinaserranomontes the branch is conflict.

**Comment by marinaserranomontes** [comment]
@Lucashuang0802 thanks! yep, I will review it, but please @adrice727 @Lucashuang0802 could you review the doc? I have already done it for Android. thanks!!

**Comment by Lucashuang0802** [comment]
👍

**Comment by Lucashuang0802** [comment]
This PR is replaced by #151.

**Pull request closed without merging**
